### ISSUE TITLE
feat: support SARIF as the reporting format

### ISSUE THREAD

**Issue by agdimech** [cdklabs/cdk-nag#1144]
### Description

[SARIF](https://sarifweb.azurewebsites.net/) is the industry standard for vulnerability reporting and should be adopted as the de-facto report format.

### Use Case

Ability to import SARIF reports into 3p tools i.e. CodeCatalyst.

### Proposed Solution

Change/add a new output format for reports using SARIF.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
This would be nice to have, but I don't think it's currently possible for a few reasons.

1. cdk-nag only works within the constraints of Aspects. There is no way to know in advance what the "last Aspect" is which is why a CSV format is used. We can append to the end of a file, but can't do any post processing

2. Aspects currently don't have the concept of line numbers or files, errors are reported on construct path. Line numbers and file location are required for SARIF
