### ISSUE TITLE
Python access to the individual rules inside cdk-nag

### ISSUE THREAD

**Issue by Jacco** [cdklabs/cdk-nag#1177]
### General Issue

Usability of internals

### The Question

As a developer of my own pack in python I want to be able to use the rules that are inside cdk-nag.

Currently the checks are not exposed in python through jsii. There is no way to get to the individual rule code.

The rule sets could be exposed like this:
```python
from cdk_nag import (
    rules_s3 as s3
)
```

Here is an example of what I would like to be able to do:
```python
import cdk_nag
from cdk_nag import (
    rules_s3 as s3
)

@jsii.implements(cdk_nag.IApplyRule)
class S3BucketSslRequestsOnly():
    def rule(self, node) -> cdk_nag.NagRuleCompliance:
        return s3.S3BucketSSLRequestsOnly(node)

    @property
    def node(self) -> cdk.CfnResource:
        return self._node
    
    @property
    def explanation(self) -> str:
        return 'S3 BucketPolicy must have a Deny statement with the condition "aws:SecureTransport" for "s3:*".'

    @property
    def rule_suffix_override(self) -> str:
        return 'FSBP-S3.1'

    @property
    def info(self) -> str:
        return 'S3 BucketPolicies must enforce SSL traffic.'
    
    @property
    def level(self) -> cdk_nag.NagMessageLevel:
        return cdk_nag.NagMessageLevel.ERROR

    def __init__(self, node) -> None:
        super().__init__()
        self._node = node

class MyPack(cdk_nag.NagPack):
    def __init__(self, **kwargs):
        super().__init__(verbose=True, **kwargs)
        self._pack_name = 'MyPack'
    
    def visit(self, node: IConstruct) -> None:
        if isinstance(node, cdk.CfnResource):
            self._apply_rule(S3BucketSslRequestsOnly(node))
```

### cdk-nag version

2.21.75

### Language

Python

### Other information

I might be able to make a PR for this request myself. Would first like to know if this request meets the tenets of the project.

**Comment by dontirun** [comment]
I think this is worth looking into and resolving given there are no breaking changes or convoluted implementations required.

The `rules` package[ is exported ](https://github.com/cdklabs/cdk-nag/blob/15b40b456cbe80326a56fad5c4bf04ab54c2fead/src/index.ts#L14) so it's possible that the changes may just be some additional steps.

On a related note, have you been successful in creating your own rules/packs in python? I haven't attempted it myself, but I think it would be nice to add to the [developer documentation](https://github.com/cdklabs/cdk-nag/tree/main/docs) if it is

**Comment by Jacco** [comment]
Hi Arun,

The above works. I saw that the rules are exported but I have not been able to find them in python.

Regards, Jacco

**Comment by dontirun** [comment]
It looks like this is occurring because the `rules` package is not exporting any classes and only functions. 

I did some preliminary testing for a fix (creating new classes with static methods), it's possible but would require quite a bit of code refactoring in the `cdk-nag` repo with some potential breaking changes (due to `jsii` naming conventions). 

Depending on the extent of the breaking changes, it ultimately may not be worth the effort

**Comment by wolfm89** [comment]
We are trying to create our own rule pack in python by adding existing rules but this issue is preventing us from doing so.
As a workaround, is it possible to use one of the existing nag packs but apply a whitelisting instead of a suppression? Like saying "We use the AWSSolutions pack but we only activate these four rules"?

**Comment by dontirun** [comment]
> As a workaround, is it possible to use one of the existing nag packs but apply a whitelisting instead of a suppression? 


From a technical standpoint I don't think there is much of a difference between those two features besides possible less reporting with allowed rules.

>Like saying "We use the AWSSolutions pack but we only activate these four rules"?

I don't think that modifying a specific pack and reporting it as the same pack is  a good approach. Each of the packs are based on sets of guidance and modifying them is not that guidance.

**Comment by wolfm89** [comment]
The point is, we are using Python and want to create our own NagPack with rules that are already defined in cdk-nag. That is currently not possible. Correct?
Can we maybe assist in implementing this feature? If you outline the approach we could maybe spend 1-2 days on it.

**Comment by dontirun** [comment]
Ultimately this would require  moving the `rules` to static classes that export functions so that the `rules` class could be compiled to other languages with `JSII`.

I previously tested this, and while it did work it resulting a number of changes that I ultimately think make the refactor a bad idea

**Breaking changes**

1. The `rules` module would have to be renamed `Rules` breaking any current developers
2. Each rule function name would have to change from `PascalCase` to `camelCase` breaking current suppressions and rule naming conventions
   - There are ways around this, like overriding every single rule name in each pack or programmatically forcing  each rule name to be PascalCase when generating the rule id which could be looked into further
   
 **Usability/Layout**
Moving to static classes that export functions makes it would make it so that individual rules wouldn't be in separate files or would have to use some complicated import process into the Static Classes. This makes it harder to test/iterate on individual rules

**Comment by dontirun** [comment]
I'd also like to understand the intended distribution model of the NagPacks. Are they meant to be localized to an individual project or are they meant to be used across multiple projects?

**Comment by wolfm89** [comment]
> I'd also like to understand the intended distribution model of the NagPacks. Are they meant to be localized to an individual project or are they meant to be used across multiple projects?

They are meant for a single project (might be extended in the future). Would there be a different approach for that?

**Comment by dontirun** [comment]
Giiven the current state, here are my suggestions

For multiple Python projects, the new pack can be written in Typescript and compiled for usage in Python (like cdk-nag is)

For a single Python project you could 
1. Follow the approach for multiple Python projects
2. Use the AwsSolutions NagPack as is and suppress the rules that you do not need to follow using a stack Suppression

**Comment by dontirun** [comment]
Yes, it's the only way that is currently supported.

**Comment by dontirun** [comment]
> If it's not planned at all to allow access for individual rules this makes the cdk-nag useful only in two cases:
> 
> 1. Your project language is JS
> 2. You plan to work only with packs provided by AWS
> 
> Both cases make this tool very limited in usage :(

I understand that this isn't a great workflow fora pack intended to be used in a single project , but you can create rules and packs using Typescript and transpile them to other languages if you want to use any prebuilt rules.

**Comment by otakusid** [comment]
Yes, for sure. But the one of key features of CDK is that it is available for different languages out of the box. There is no requirement to write some constructs in Typescript and transpile them to other languages.

So tools that are designed to work with CDK are expected to have such features too - I expect that I will be available to use all functionality of the tool without the requirement to write some part on Typescript. Maybe not from the start, but at least at some nearest future

In the case of cdk-nag there is no prebuild rules pack for f.e. AWS CIS Benchmark that is widely used as a basic framework to align infrastructure with. It is available in the SecurityHub, but the is no way to run CIS checks with such a great tool as cdk-nug, to shorten the feedback loop :(

There is no problem in general because a lot of CIS rules are defined in the different packs and I can reuse them with small efforts for writing some unique for CIS ones. But I can't do this without injecting Typescript to my dev stack and as I understand that's even not planned anymore :(
