### ISSUE TITLE
feat: Add S3DefaultEncryptionKMS to AWSSolutionsChecks

### ISSUE THREAD

**Issue by rinaudjaws** [cdklabs/cdk-nag#1364]
### Description

S3 Encryption should be included in AWSSolutionsChecks packs as it's a general AWS best practice.

### Use Case

Needed to run NIST checks only to identify which buckets were not encrypted.

### Proposed Solution

See description.

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
It is no longer necessary to check for S3 Server Side Encryption as [S3 now encrypts all objects](https://aws.amazon.com/blogs/aws/amazon-s3-encrypts-new-objects-by-default/) by default. 

The rule that checked for S3 SSE [was removed](https://github.com/cdklabs/cdk-nag/issues/1190) due to this new feature.


Some compliance standards (like NIST) require KMS encryption for S3 which is why that rule exists in other packs. The AWS Solutions guidance does not require KMS encryption so this rule won't be added there.

**Comment by rinaudjaws** [comment]
While valid, this doesn't take into consideration creation date of the bucket. The result is the real encryption status is ignored for CDK stacks deployed before 2023. Customers need then to rely on AWS Security Hub or AWS Config to check their real posture.

**Comment by dontirun** [comment]
I believe this change applies to all new objects on buckets regardless of when they were created
