### ISSUE TITLE
feat: Separate exemptions into cdk context or a different file

### ISSUE THREAD

**Issue by khan-a1** [cdklabs/cdk-nag#518]
### Description

Including Stack level suppression logic for each stack adds a lot of redundant code imo. It would be nice if cdk-nag can automatically read the exemptions from cdk context file or a dedicated file for exemptions

### Use Case

Rather than adding exemption code everywhere, I would prefer defining my per stack exemptions in a single file with default name and location that cdk-nag can read and add the exemptions for me.

### Proposed Solution

Add new feature that allows to define the exemptions in cdk context or a separate json file and is read automatically by cdk-nag. It should check if the file exists or entries in context file and apply them. Potentially any local ones manually added at stack level using NagSuppressions.addStackSuppressions should be merged with the file ones 

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
I like the overall idea, but let's refine the use case. 
1. I like the idea of having an option to read exceptions from a well-known file (`cdk.json` being a good candidate), but I dislike the idea of "auto-application" of suppressions since suppressions of rules should be deliberate. I think the compliance logic should live with the code to make code reviews more transparent.   
2. I think this is useful beyond just Stack level suppressions and can be used on resource suppressions as well 

Given the above I think a method like the following could help

```typescript
  /**
   * Generate suppressions from the specified key in the cdk context.
   * @param node The App or Construct to read the context from.
   * @param key The key name in the cdk context.
   * @returns The NagSuppressions generated from the context key.
   */
  static suppressionsFromContext(
    node: App | IConstruct,
    key: string,
  ): NagPackSuppression[]
```

The various suppression methods (`Stack`, and`Resource`) could then be updated to accept either a `NagPackSuppression[]` or a `string` with the name of the context variable and use the above method

```typescript
  static addStackSuppressions(
    stack: Stack,
    suppressions: NagPackSuppression[] | string,
    applyToNestedStacks: boolean = false
  ){}

  static addResourceSuppressions(
    construct: IConstruct,
    suppressions: NagPackSuppression[] | string,
    applyToChildren: boolean = false
){}
```

Which allows the user to do the following

```typescript
Aspects.of(app).add(new AwsSolutionsChecks());
NagSuppressions.addStackSuppressions(stack, 'name-of-context-variable`)
```

I think this strikes a good balance between ease of use and transparency. Does this solve the use case? Happy to discuss further.

**Comment by khan-a1** [comment]
Hi @dontirun - I like that, explicit yet neat! just wondering if we need to pass in the context variable name? it could use a default one like 'stackname/nestedstackname-cfn-nag-exemptions'? and the methods could check if a string is passed for the context key, use it to lookup context file and if not, build the default one and use it?

Potentially a new Enum value NagSuppressions.USE_DEFAULT_CONTEXT_KEY or something to hint to use the default name

**Comment by dontirun** [comment]
I think that would remove transparency from a code review perspective by making it hard to trace what is happening. In that case you could do something like the following to achieve the same result

```typescript
NagSuppressions.addStackSuppressions(stack, stack.name)
```

**Comment by khan-a1** [comment]
I would then prefer your original suggestion of passing in the context file key name - that allows for more flexibility and control.
