### ISSUE TITLE
feat: make rendering suppression metadata optional

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [cdklabs/cdk-nag#845]
### Description

Please add the ability to opt out of rendering nag rule suppression metadata into the synth'd cloudformation stack templates of a CDK application.

Related: #837

### Use Case

My organization considers our CDK code as the source of truth for our infra as code. Rendering the suppressed nag rules into the cloudformation template provides us with little to no value and increases the size of our templates unnecessarily.

### Proposed Solution

An opt-out can be implemented as a NagPack-level property controlling the behavior, e.g.:

```ts
new HIPAASecurityChecks({
    addRulesToMetadata: false,
});
```

To preserve the existing behavior, this new property can have a default value of `true`.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
This would take a large amount of breaking refactoring to implement. The `Suppression` and `Rules` systems are completely independent of one another and use the CloudFormation template metadata to communicate between one another. In order to implement this each instance of a `NagPack` would need its own in memory suppression system.

1. [Rules system reading suppressions](https://github.com/cdklabs/cdk-nag/blob/81e6b59ebfebbfc70c820b41a76aac4c1384de19/src/utils/nag-suppression-helper.ts#L53)
2. [Suppressions being applied](https://github.com/cdklabs/cdk-nag/blob/81e6b59ebfebbfc70c820b41a76aac4c1384de19/src/utils/nag-suppression-helper.ts#L38)

**Comment by vito-laurenza-zocdoc** [comment]
Was this implemented?

**Comment by dontirun** [comment]
No due to the reasons I wrote above
